
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py


mf_struct = []
NUM_OF_ENTRIES = 0
def get_new_row():
    # max should be initialized as -1 instead of 0
    return {
        "cust": "",
        "year": "",
        
        "q1_sum_quant": 0,
        "q1_avg_quant": 0,
        "q2_sum_quant": 0,
        "q2_avg_quant": 0,
        "q3_sum_quant": 0,
        "q3_avg_quant": 0,
        "q1_count_quant": 0,
        "q2_count_quant": 0,
        "q3_count_quant": 0,
        
    }

def lookup(cur_row):
    for i in range(NUM_OF_ENTRIES):
        if (mf_struct[i]["cust"] == cur_row["cust"] and mf_struct[i]["year"] == cur_row["year"]):
            return i
    return -1

def add(cur_row, mf_struct):
    global NUM_OF_ENTRIES
    newrow = get_new_row()
    newrow["cust"] = cur_row["cust"]
    newrow["year"] = cur_row["year"]
    
    mf_struct.append(newrow)
    NUM_OF_ENTRIES = NUM_OF_ENTRIES + 1

def output():
    print(". . . . .\n"); # header of the output (from operand S)
    for i in range(NUM_OF_ENTRIES):
        if mf_struct[i]["q1_avg_quant"] > mf_struct[i]["q2_avg_quant"] and mf_struct[i]["q2_avg_quant"] > mf_struct[i]["q3_avg_quant"]:
            print("%s	%s	%s	%s	%s	\n" % (mf_struct[i]["cust"], mf_struct[i]["year"], mf_struct[i]["q1_sum_quant"], mf_struct[i]["q2_sum_quant"], mf_struct[i]["q3_sum_quant"], ))


def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    
    # TABLE SCAN 1
    table = cur.fetchall()
    columns = [desc[0] for desc in cur.description]
    table = [dict(zip(columns, row)) for row in table]
    for row in table:
        pos = lookup(row)
        if pos == -1:
            add(row, mf_struct)
    
    
    for row in table:
        if m:
            pos = lookup(row)
            if pos != -1:
                mf_struct[pos]["q1_sum_quant"] += row["quant"]
                mf_struct[pos]["q1_avg_quant"] += row["quant"]
                
    
    for row in table:
        if o:
            pos = lookup(row)
            if pos != -1:
                mf_struct[pos]["q2_sum_quant"] += row["quant"]
                mf_struct[pos]["q2_avg_quant"] += row["quant"]
                
    
    for row in table:
        if n:
            pos = lookup(row)
            if pos != -1:
                mf_struct[pos]["q3_sum_quant"] += row["quant"]
                mf_struct[pos]["q3_avg_quant"] += row["quant"]
                
    
    for i in range(NUM_OF_ENTRIES):
        
        if mf_struct[i]["q1_count_quant"] != 0:
            mf_struct[i]["q1_avg_quant"] /= mf_struct[i]["q1_count_quant"]
    
        if mf_struct[i]["q2_count_quant"] != 0:
            mf_struct[i]["q2_avg_quant"] /= mf_struct[i]["q2_count_quant"]
    
        if mf_struct[i]["q3_count_quant"] != 0:
            mf_struct[i]["q3_avg_quant"] /= mf_struct[i]["q3_count_quant"]
            

    output()


    cur.close()
    conn.close()
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    