import subprocess

# Stuff up here is being put in python format for generation

            


def main(phi):

    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """
    S = phi[0]
    n = phi[1]
    V = phi[2]
    FVECT = phi[3]
    PRED_LIST = phi[4]
    HAVING = phi[5]
    groupingvars = ""
    for i in range(n):
        groupingvars = groupingvars + f"{S[i - n]} = 0\n"

    print(groupingvars)

    body = f"""
    class struct:
        def __init__():
            {S[0]} = [' '] * 50 # not entirely sure where this 50 comes from. also needs handling for multiple basic variables
            {groupingvars}

    mf_struct = struct()
    NUM_OF_ENTRIES = 0

    def lookup(cur_row):
        for i in range(NUM_OF_ENTRIES):
            if (mf_struct[i].{S[0]} == cur_row.{S[0]}):
                return i
        return -1

    def add(cur_row):
        mf_struct[NUM_OF_ENTRIES].{S[0]} = cur_row.{S[0]}
        # add handling here for the various quants
        NUM_OF_ENTRIES = NUM_OF_ENTRIES + 1

    def output():
        print(". . . . .\\n"); # header of the output (from operand S)
        for i in range(NUM_OF_ENTRIES):
            print("%s %d %d %d\\n", mf_struct[i].{S[0]}, mf_struct[i].count_1_quant, mf_struct[i].sum_2_quant, mf_struct[i].max_3_quant); # replace quant handling here with proper variables
    # TABLE SCAN 1: populate mf-struct with distinct values of grouping attribute (V)
    while True:
        if cur == -1: # i dont actually know how to check if the cursor's at the end of the table
            break
        pos = lookup(cur)
        if pos == -1:
            add(cur)
        cur.next() # move to the next row, check how to do that
    """

    for i in range(n):
        body = body + f"""
    while True:

        if cur == -1: # i dont actually know how to check if the cursor's at the end of the table
            break
        if {PRED_LIST[i]}:
        
            # look up current_row.cust in mf_struct
            pos = lookup(cur, mf_struct)
            # current_row.cust found in mf_struct

            # handling for necessary quants (sum, max, min, avg, count)
        
        cur.next() # move to the next row, check how to do that
"""
    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    {body}
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code
    subprocess.run(["python", "_generated.py"])


if "__main__" == __name__:
    main()
