import subprocess

# Stuff up here is being put in python format for generation

            


def main(phi):

    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """
    S = phi[0]
    n = phi[1]
    V = phi[2]
    FVECT = phi[3]
    PRED_LIST = phi[4]
    HAVING = phi[5]

    aggfuncs = ""
    for i in range(len(FVECT)):
        aggfuncs = aggfuncs + f"{FVECT[i]}: 0,\n"
    print(aggfuncs)
    
    groupingattrs = ""
    for i in range(len(V)):
        groupingattrs = groupingattrs + f"\"{V[i]}\": "",\n"
    
    groupadd = ""
    for i in range(len(V)):
        groupadd = groupadd + f"newrow[\"{V[i]}\"] = cur[\"{V[i]}\"]\n"
    
    outputlist = ""
    outputstring = ""
    for i in range(len(S)):
        outputlist = outputlist + "mf_struct[i][\"" + S[i] + "\"], "
        if S[i] in FVECT:
            outputstring = outputstring + "%d\t"
        else:
            outputstring = outputstring + "%s\t"
    
    lookupcondition = []
    for i in range(len(V)):
        lookupcondition.append(f"mf_struct[i][\"{V[i]}\"] == cur[\"{V[i]}\"]")
    lookupcondition = " and ".join(lookupcondition)
    
    processgroupvars = ""
    for i in range(n):
        processgroupvars = processgroupvars + f"""
    for row in table:
        if {PRED_LIST[i]}: # unsure if this matches, just going w/ it for now
            pos = lookup(row)
            if pos != -1:
                mf_struct[pos][\"{FVECT[i]}\"] += 1 # this is just sum
    """


    body = f"""
    def row():
        # max should be initialized as -1 instead of 0
        return {{
            {groupingattrs}
            {aggfuncs}
        }}
    mf_struct = []
    NUM_OF_ENTRIES = 0

    def lookup(cur_row):
        for i in range(NUM_OF_ENTRIES):
            if ({lookupcondition}):
                return i
        return -1

    def add(cur_row):
        newrow = row()
        {groupadd}
        mf_struct.append(newrow)
        NUM_OF_ENTRIES = NUM_OF_ENTRIES + 1

    def output():
        print(". . . . .\\n"); # header of the output (from operand S)
        for i in range(NUM_OF_ENTRIES):
            print("{outputstring}\\n", {outputlist});
    
    # TABLE SCAN 1
    table = cur.fetchall()
    for row in table:
        pos = lookup(row)
        if pos == -1:
            add(row)
    
    {processgroupvars}        

    output()

"""
    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    {body}
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code
    subprocess.run(["python", "_generated.py"])


if "__main__" == __name__:
    main()
