import subprocess, parser

# Stuff up here is being put in python format for generation

def editcondition(precond, cond, attrs):
    havingcond = "" 
    havinglist = cond.split(" ")
    for i in range(len(havinglist)):
        if havinglist[i] in attrs:
            havingcond = havingcond + f"{precond}[\"{havinglist[i]}\"] "
        else:
            havingcond = havingcond + havinglist[i] + " "
    havingcond = havingcond.strip()
    return havingcond


SCHEMA = ["cust", "prod", "day", "month", "year", "state", "quant", "date"]

def getcol(agg):
    for attr in SCHEMA:
        if attr in agg:
            return attr

def main(phi):
    """
    This is the generator code. It should take in the MF structure and generate the code
    needed to run the query. That generated code should be saved to a 
    file (e.g. _generated.py) and then run.
    """
    for x in range(len(phi)):
        if type(phi[x]) == list:
            for y in range(len(phi[x])):
                phi[x][y] = phi[x][y].strip()
    S = phi[0]
    n = phi[1]
    V = phi[2]
    FVECT = phi[3]
    PRED_LIST = phi[4]
    HAVING = phi[5]

    havingcond = editcondition("mf_struct[i]", HAVING, V + FVECT)

    aggfuncs = ""
    for i in range(len(FVECT)):
        aggfuncs = aggfuncs + f"\"{FVECT[i]}\": 0,\n           "
    
    groupingattrs = ""
    for i in range(len(V)):
        groupingattrs = groupingattrs + f"\"{V[i]}\": \"\",\n           "
    
    groupadd = ""
    for i in range(len(V)):
        groupadd = groupadd + f"newrow[\"{V[i]}\"] = cur_row[\"{V[i]}\"]\n"
    
    outputlist = ""
    outputstring = ""
    for i in range(len(S)):
        outputlist = outputlist + "mf_struct[i][\"" + S[i] + "\"], "
        if S[i] in FVECT:
            outputstring = outputstring + "%d\t"
        else:
            outputstring = outputstring + "%s\t"
    
    lookupcondition = []
    for i in range(len(V)):
        lookupcondition.append(f"mf_struct[i][\"{V[i]}\"] == cur_row[\"{V[i]}\"]")
    lookupcondition = " and ".join(lookupcondition)
    
    processgroupvars = ""
    for i in range(n):
        action = ""
        if "sum" in FVECT[i]:
            action = action + f"mf_struct[pos][\"{FVECT[i]}\"] += row[\"{getcol(FVECT[i])}\"]\n"
        elif "avg" in FVECT[i]:
            action = action + f"mf_struct[pos][\"{FVECT[i]}\"] += row[\"{getcol(FVECT[i])}\"]\n"
        elif "max" in FVECT[i]:
            action = action + f"""
    if row[\"{getcol(FVECT[i])}\"] > mf_struct[pos][\"{FVECT[i]}\"]:
        mf_struct[pos][\"{FVECT[i]}\"] = row[\"{getcol(FVECT[i])}\"]
    """
        elif "min" in FVECT[i]:
            action = action + f"""
    if row[\"{getcol(FVECT[i])}\"] < mf_struct[pos][\"{FVECT[i]}\"]:
        mf_struct[pos][\"{FVECT[i]}\"] = row[\"{getcol(FVECT[i])}\"]
    """

        processgroupvars = processgroupvars + f"""
    for row in table:
        if {editcondition("row", PRED_LIST[i], SCHEMA)}:
            pos = lookup(row)
            if pos != -1:
                {action}
    """


    body = f"""
    def row():
        # max should be initialized as -1 instead of 0
        return {{
            {groupingattrs}
            {aggfuncs}
        }}
    mf_struct = []
    NUM_OF_ENTRIES = 0

    def lookup(cur_row):
        for i in range(NUM_OF_ENTRIES):
            if ({lookupcondition}):
                return i
        return -1

    def add(cur_row):
        newrow = row()
        {groupadd}
        mf_struct.append(newrow)
        NUM_OF_ENTRIES = NUM_OF_ENTRIES + 1

    def output():
        print(". . . . .\\n"); # header of the output (from operand S)
        for i in range(NUM_OF_ENTRIES):
            if {havingcond}:
                print("{outputstring}\\n", {outputlist});
    
    # TABLE SCAN 1
    table = cur.fetchall()
    for row in table:
        pos = lookup(row)
        if pos == -1:
            add(row)
    
    {processgroupvars}        

    output()

"""
    # Note: The f allows formatting with variables.
    #       Also, note the indentation is preserved.
    tmp = f"""
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    {body}
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    """

    # Write the generated code to a file
    open("_generated.py", "w").write(tmp)
    # Execute the generated code
    subprocess.run(["python", "_generated.py"])


if "__main__" == __name__:
    phi = parser.get_test_input_query()
    main(phi)
